browser=chromium
headless=true
maximize=true
pageLoadTimeout=40000
trace.enabled=true
trace.retainOnFailureOnly=true
#defaultTimeoutMs=40000
#se implementara un mentodo para la siguiente version
implicitWait=10