env=qa

# Demo app (we?ll use it in Level 6+ for login)
app.url.dev=https://www.saucedemo.com
app.url.qa=https://oim.pre.mapfre.com.pe/#/login
app.url.prod=https://www.saucedemo.com
#report.screenshots.dir=target/screenshots

# Global UI synchronization
ui.spinner.xpath=//div[contains(@class,'spinner')]
ui.spinner.quietMs=250
ui.spinner.timeoutMs=120000

ui.screenshot.checkpoints.enabled=true

# Credenciales
user.email=WEBMASTER
user.password=Mapfre123.